services:
  - type: worker
    name: bitcoin-etl-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/pipeline.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoin-db
          property: connectionString
